
module.exports = [
  'comment',
  'custom_json',
  'transfer',
  'account_witness_vote',
  'restaurantStatus',
  'withdraw_vesting',
  'withdraw_route',
  'fillOrder',
  'rejectUpdate',
  'changePassword',
  'transfer_to_vesting',
  'change_recovery_account',
  'transfer_from_savings',
  'activateCampaign',
  'suspendedStatus',
  'claimReward',
  'like',
];
