exports.TYPES = {
  website_account_suspended: 'Attention! All your websites are now suspended due to the negative balance on your website account',
  balance_run_out_three_months: 'Warning: website account balance may run out in three months',
  balance_run_out_two_months: 'Warning: website account balance may run out in two months',
  balance_run_out_month: 'Warning: website account balance may run out in a month',
  balance_run_out_three_weeks: 'Warning: website account balance may run out in three weeks',
  balance_run_out_two_weeks: 'Warning: website account balance may run out in two weeks',
  balance_run_out_week: 'Warning: website account balance may run out in a week',
  balance_run_out_six_days: 'Warning: website account balance may run out in six days',
  balance_run_out_five_days: 'Warning: website account balance may run out in five days',
  balance_run_out_four_days: 'Warning: website account balance may run out in four days',
  balance_run_out_three_days: 'Warning: website account balance may run out in three days',
  balance_run_out_two_days: 'Warning: website account balance may run out in two days',
  balance_run_out_day: 'Warning: website account balance may run out in a day',
};
exports.NOTIFICATIONS_TYPES = {
  CHANGE_RECOVERY_ACCOUNT: 'change_recovery_account',
  TRANSFER_FROM_SAVINGS: 'transfer_from_savings',
  ACCOUNT_WITNESS_VOTE: 'account_witness_vote',
  CAMPAIGN_RESERVATION: 'campaignReservation',
  TRANSFER_TO_VESTING: 'transfer_to_vesting',
  ACTIVATE_CAMPAIGN: 'activationCampaign',
  DEACTIVATE_CAMPAIGN: 'deactivationCampaign',
  BELL_WOBJ_REWARDS: 'bellWobjectRewards',
  GET_NOTIFICATIONS: 'get_notifications',
  RESTAURANT_STATUS: 'restaurantStatus',
  WITHDRAW_VESTING: 'withdraw_vesting',
  SUSPENDED_STATUS: 'suspendedStatus',
  CAMPAIGN_MESSAGE: 'campaignMessage',
  WEB_SITE_BALANCE: 'webSiteBalance',
  CHANGE_PASSWORD: 'changePassword',
  WITHDRAW_ROUTE: 'withdraw_route',
  TRANSFER_FROM: 'transferFrom',
  REJECT_UPDATE: 'rejectUpdate',
  STATUS_CHANGE: 'statusChange',
  NOTIFICATION: 'notification',
  WITNESS_VOTE: 'witness_vote',
  CLAIM_REWARD: 'claimReward',
  CUSTOM_JSON: 'custom_json',
  VIP_TICKETS: 'vipTickets',
  POWER_DOWN: 'power_down',
  MY_COMMENT: 'myComment',
  FILL_ORDER: 'fillOrder',
  HEARTBEAT: 'heartbeat',
  TRANSFER: 'transfer',
  COMMENT: 'comment',
  MENTION: 'mention',
  MY_POST: 'myPost',
  MY_LIKE: 'myLike',
  LOGIN: 'login',
  REPLY: 'reply',
  LIKE: 'like',
};

exports.CUSTOM_JSON_IDS = {
  FOLLOW: 'follow',
  REBLOG: 'reblog',
};

exports.BELL_NOTIFICATIONS = {
  BELL_WOBJ_REWARDS: 'bellWobjectRewards',
  BELL_WOBJ_POST: 'bellWobjectPost',
  BELL_REBLOG: 'bellReblog',
  BELL_FOLLOW: 'bellFollow',
  BELL_POST: 'bellPost',
};

exports.CALL_METHOD = {
  GET_NOTIFICATIONS: 'get_notifications',
  SUBSCRIBE_TICKET: 'subscribeTicket',
  SUBSCRIBE_BLOCK: 'subscribeBlock',
  GUEST_LOGIN: 'guest_login',
  UNSUBSCRIBE: 'unsubscribe',
  SUBSCRIBE: 'subscribe',
  LOGIN: 'login',
};
