exports.TYPES = {
  website_account_suspended: 'Attention! All your websites are now suspended due to the negative balance on your website account',
  balance_run_out_three_months: 'Warning: website account balance may run out in 3 months',
  balance_run_out_two_months: 'Warning: website account balance may run out in 2 months',
  balance_run_out_month: 'Warning: website account balance may run out in a month',
  balance_run_out_three_weeks: 'Warning: website account balance may run out in 3 weeks',
  balance_run_out_two_weeks: 'Warning: website account balance may run out in 2 weeks',
  balance_run_out_week: 'Warning: website account balance may run out in a week',
  balance_run_out_six_days: 'Warning: website account balance may run out in 6 days',
  balance_run_out_five_days: 'Warning: website account balance may run out in 5 days',
  balance_run_out_four_days: 'Warning: website account balance may run out in 4 days',
  balance_run_out_three_days: 'Warning: website account balance may run out in 3 days',
  balance_run_out_two_days: 'Warning: website account balance may run out in 2 days',
  balance_run_out_day: 'Warning: website account balance may run out in a day',
};
exports.NOTIFICATIONS_TYPES = {
  CHANGE_RECOVERY_ACCOUNT: 'change_recovery_account',
  TRANSFER_FROM_SAVINGS: 'transfer_from_savings',
  ACCOUNT_WITNESS_VOTE: 'account_witness_vote',
  CAMPAIGN_RESERVATION: 'campaignReservation',
  TRANSFER_TO_VESTING: 'transfer_to_vesting',
  ACTIVATE_CAMPAIGN: 'activationCampaign',
  DEACTIVATE_CAMPAIGN: 'deactivationCampaign',
  BELL_WOBJ_REWARDS: 'bellWobjectRewards',
  GET_NOTIFICATIONS: 'get_notifications',
  RESTAURANT_STATUS: 'restaurantStatus',
  WITHDRAW_VESTING: 'withdraw_vesting',
  HIVE_ENGINE_DELAY: 'hiveEngineDelay',
  SUSPENDED_STATUS: 'suspendedStatus',
  CAMPAIGN_MESSAGE: 'campaignMessage',
  WEB_SITE_BALANCE: 'webSiteBalance',
  CHANGE_PASSWORD: 'changePassword',
  WITHDRAW_ROUTE: 'withdraw_route',
  TRANSFER_FROM: 'transferFrom',
  UNDELEGATE: 'undelegate',
  DELEGATE_VESTING_SHARES: 'delegate_vesting_shares',
  CANCEL_UNSTAKE: 'cancelUnstake',
  REJECT_UPDATE: 'rejectUpdate',
  STATUS_CHANGE: 'statusChange',
  NOTIFICATION: 'notification',
  WITNESS_VOTE: 'witness_vote',
  CLAIM_REWARD: 'claimReward',
  CUSTOM_JSON: 'custom_json',
  VIP_TICKETS: 'vipTickets',
  POWER_DOWN: 'power_down',
  MY_COMMENT: 'myComment',
  FILL_ORDER: 'fillOrder',
  HEARTBEAT: 'heartbeat',
  TRANSFER: 'transfer',
  DELEGATE: 'delegate',
  UNSTAKE: 'unstake',
  COMMENT: 'comment',
  MENTION: 'mention',
  MY_POST: 'myPost',
  MY_LIKE: 'myLike',
  LOGIN: 'login',
  REPLY: 'reply',
  STAKE: 'stake',
  LIKE: 'like',
  ARBITRAGE: 'arbitrage',
  UPDATE_INFO: 'updateInfo',
};

exports.CUSTOM_JSON_IDS = {
  FOLLOW: 'follow',
  REBLOG: 'reblog',
};

exports.BELL_NOTIFICATIONS = {
  BELL_WOBJ_REWARDS: 'bellWobjectRewards',
  BELL_WOBJ_POST: 'bellWobjectPost',
  BELL_REBLOG: 'bellReblog',
  BELL_FOLLOW: 'bellFollow',
  BELL_POST: 'bellPost',
};

exports.CALL_METHOD = {
  GET_NOTIFICATIONS: 'get_notifications',
  SUBSCRIBE_TICKET: 'subscribeTicket',
  SUBSCRIBE_BLOCK: 'subscribeBlock',
  SUBSCRIBE_CAMPAIGN_ASSIGN: 'subscribeCampaignAssign',
  GUEST_LOGIN: 'guest_login',
  UNSUBSCRIBE: 'unsubscribe',
  SUBSCRIBE: 'subscribe',
  LOGIN: 'login',
  SET_NOTIFICATION: 'setNotification',
  UPDATE_INFO: 'updateInfo',
};

exports.ENGINE_CHAIN_STATUSES = {
  WARNING: 'WARNING',
  OK: 'OK',
};
