module.exports = {
  changeRecoveryAccount: require('./changeRecoveryAccount'),
  transferFromSavings: require('./transferFromSavings'),
  deactivateCampaign: require('./deactivateCampaign'),
  transferToVesting: require('./transferToVesting'),
  activateCampaign: require('./activateCampaign'),
  restaurantStatus: require('./restaurantStatus'),
  suspendedStatus: require('./suspendedStatus'),
  withdrawVesting: require('./withdrawVesting'),
  campaignMessage: require('./campaignMessage'),
  changePassword: require('./changePassword'),
  mainOperations: require('./mainOperations'),
  webSiteBalance: require('./webSiteBalance'),
  wobjectReward: require('./wobjectReward'),
  withdrawRoute: require('./withdrawRoute'),
  rejectUpdate: require('./rejectUpdate'),
  witnessVote: require('./witnessVote'),
  claimReward: require('./claimReward'),
  customJson: require('./customJson'),
  fillOrder: require('./fillOrder'),
  transfer: require('./transfer'),
  comment: require('./comment'),
  like: require('./like'),
};
